# ЛА прямые методы решения СЛАУ

Пусть задана система линейных алгебраических уравнений, которую необходимо решить (найти такие значения хi, которые обращают каждое уравнение системы в равенство).

Мы знаем, что система линейных алгебраических уравнений может:

1) Не иметь решений (быть несовместной)

2) Иметь бесконечно много решений

3) Иметь единственное решение

Правило Крамера и матричный метод непригодны в тех случаях, когда система имеет бесконечно много решений или несовместна.

**Метод Гаусса** – гораздо более мощный и универсальный инструмент для нахождения решения любой системы линейных уравнений, который в любом случае приведет нас к ответу!

Сам алгоритм метода во всех трёх случаях работает одинаково.



Преобразования расширенной матрицы (это матрица системы - матрица, составленная только из коэффициентов при неизвестных, плюс столбец свободных членов) системы линейных алгебраических уравнений в методе Гаусса:

1) строки матрицы можно переставлять местами

2) если в матрице появились (или есть) пропорциональные (или вообще одинаковые) строки, то следует удалить из матрицы все эти строки кроме одной

3) если в матрице в ходе преобразований появилась нулевая строка, то ее также следует удалить

4) строку матрицы можно умножить (разделить) на любое число,отличное от нуля

5) к строке матрицы можно прибавить другую строку, умноженную на число , отличное от нуля

В методе Гаусса такие элементарные преобразования не меняют решение системы уравнений

Метод Гаусса состоит из двух этапов:

**Прямой ход** - с помощью элементарных преобразований привести расширенную матрицу системы линейных алгебраических уравнений к «треугольному» ступенчатому виду: элементы расширенной матрицы, расположенные ниже главной диагонали, равны нулю (ход «сверху-вниз»)

Для этого:
1) Пусть мы рассматриваем первое уравнение системы линейных алгебраических уравнений и коэффициент при х1 равен k.
Второе, третье и т.д. уравнения преобразуем следующим образом: каждое уравнение (коэффициенты при неизвестных, включая свободные члены) делим на коэффициент при неизвестном х1 , стоящий в каждом уравнении, и умножаем на k. После этого из второго уравнения (коэффициенты при неизвестных и свободные члены) вычитаем первое. Получаем при х1 во втором уравнении коэффициент 0. Из третьего преобразованного уравнения вычитаем первое уравнение, так до тех пор, пока все уравнения, кроме первого, при неизвестном х 1 не будут иметь коэффициент 0.

2) Переходим к следующему уравнению. Пусть это будет второе уравнение и коэффициент при х2 равен m. Со всеми «нижестоящими» уравнениями поступаем так, как описано выше. Таким образом, «под» неизвестной х2 во всех уравнениях будут нули.

3) Переходим к следующему уравнению и так до тех пора, пока не останется одна последняя неизвестная и преобразованный свободный член.

**Обратный ход** метода Гаусса – получение решения системы линейных алгебраических уравнений (ход «снизу-вверх»). Из последнего «нижнего» уравнения получаем одно первое решение – неизвестную х n . Для этого решаем элементарное уравнение А*хn = В. В примере, приведенном выше, х3 = 4. Подставляем найденное значение в «верхнее» следующее уравнение и решаем его относительно следующей неизвестной. И так до тех пор, пока не найдем все неизвестные

**01.** Solve the equations $\mathbf{AX = B}$ by Gauss elimination, where

$$
\mathbf{A} =
\begin{bmatrix}
2& 0& −1& 0  \\
0& 1& 2& 0  \\
−1&2& 0& 1 \\
0& 0& 1& −2
\end{bmatrix}
\ \ \ \ \ \mathbf{B} =
\begin{bmatrix}
1& 0  \\
0&  0  \\
0& 1  \\
0& 0\\
\end{bmatrix}
$$

In [ ]:
%matplotlib inline
%precision 16
import numpy
import matplotlib.pyplot as plt
import sys
sys.path.append("lib")
## module LUdecomp
''' a = LUdecomp(a)
    LUdecomposition: [L][U] = [a]

    x = LUsolve(a,b)
    Solution phase: solves [L][U]{x} = {b}
'''
import numpy as np

def LUdecomp(a):
    n = len(a)
    for k in range(0,n-1):
        for i in range(k+1,n):
           if a[i,k] != 0.0:
               lam = a [i,k]/a[k,k]
               a[i,k+1:n] = a[i,k+1:n] - lam*a[k,k+1:n]
               a[i,k] = lam
    return a

def LUsolve(a,b):
    n = len(a)
    for k in range(1,n):
        b[k] = b[k] - np.dot(a[k,0:k],b[0:k])
    b[n-1] = b[n-1]/a[n-1,n-1]
    for k in range(n-2,-1,-1):
       b[k] = (b[k] - np.dot(a[k,k+1:n],b[k+1:n]))/a[k,k]
    return b

In [ ]:
import numpy as np


a = np.array([[ 2.0, 0.0, -1.0, 0.0], \
            [0.0, 1.0, 2.0, 0.0], \
            [ -1.0, 2.0, 0.0, 1.0], \
            [0.0, 0.0, 1.0, -2.0]])
b = np.array([[ 1.0, 0.0, 0.0, 0.0], \
            [0.0, 0.0, 1.0, 0.0]])

a = LUdecomp(a)
det = np.prod(np.diagonal(a))
print("\nDeterminant =",det)

for i in range(len(b)):
    x = LUsolve(a,b[i])
    print("x",i+1,"=",x)


Determinant = 16.0
x 1 = [ 0.4375  0.25   -0.125  -0.0625]
x 2 = [-0.125  0.5   -0.25  -0.125]




---



---



# ЛА итерационные методы

Итеративные методы **Якоби** и **Гаусс-Зейделя** в численном анализе основаны на идее последовательных приближений. Этот итеративный метод начинается с одного или двух начальных приближений корней, с последовательности приближений x1, x2, x3, ..., xk, ..., как k → ∞, эта последовательность корней сходится к точному корню.

Для системы уравнений Ax = B мы начинаем с начальной аппроксимации  x = x0, с помощью которой мы получаем последовательность вектора решений x1, x2, ..., xk, ... как k → ∞, эта последовательность сходится к решению x = A-1B.

*Разница между методами Гаусса-Зейделя и Якоби* заключается в том, что метод Якоби использует значения, полученные на предыдущем шаге, а метод Гаусса-Зейделя всегда применяет последние обновленные значения во время итеративных процедур

Метод Гаусса-Сейделя называют ещё методом последовательного смещения, потому что второе неизвестное определяется из первого неизвестного в текущей итерации, третье неизвестное определяется из первого и второго неизвестных и т. д.

**09.** Write a computer program to solve the following n simultaneous equations by the
Jacobi (Gauss-Seidel) method with relaxation (the program should work with any value of n)

\begin{equation*}
\left(
\begin{array}{cccccccc}
2 & −1&  0&  0& \dots & 0& 0& 0& 1  \\
−1&  2& −1&  0& \dots & 0& 0& 0& 0  \\
0 & −1&  2& −1& \dots & 0& 0& 0& 0  \\
\vdots & \vdots & \vdots & \vdots &  & \vdots & \vdots & \vdots & \vdots  \\
0 & 0& 0& 0& \dots &  −1& 2& −1& 0 \\
0 & 0& 0& 0& \dots &  0& −1& 2 &−1  \\
1 & 0& 0& 0&  \dots & 0& 0 &−1 &2  \\
\end{array}
\right)
\left(
\begin{array}{c}
x_1 \\
x_2 \\
x_3 \\
\vdots \\
x_{n−2} \\
x_{n−1} \\
x_n  \\
\end{array}
\right)=
\left(
\begin{array}{c}
0 \\
0 \\
0 \\
\vdots \\
0 \\
0 \\
1  \\
\end{array}
\right)
\end{equation*}

Run the program with $n = 20$. The exact solution can be shown to be $x_i = −n/4 + i/2$,  
$i = 1, 2, ... , n$

In [ ]:
import numpy as np
import math

def gaussSeidel(iterEqs,x,tol = 1.0e-9):
    omega = 1.0
    k = 10
    p = 1
    for i in range(1,501):
        xOld = x.copy()
        x = iterEqs(x,omega)
        dx = math.sqrt(np.dot(x-xOld,x-xOld))
        if dx < tol: return x,i,omega
      # Compute relaxation factor after k+p iterations
        if i == k: dx1 = dx
        if i == k + p:
            dx2 = dx
            omega = 2.0/(1.0 + math.sqrt(1.0 - (dx2/dx1)**(1.0/p)))
    print('Gauss-Seidel failed to converge')

In [ ]:
#!/usr/bin/python
## example
%precision 8

def iterEqs(x,omega):
    n = len(x)
    x[0] = omega*(x[1] - x[n-1])/2.0 + (1.0 - omega)*x[0]
    for i in range(1,n-1):
        x[i] = omega*(x[i-1] + x[i+1])/2.0 + (1.0 - omega)*x[i]
    x[n-1] = omega*(1.0 - x[0] + x[n-2])/2.0 \
        + (1.0 - omega)*x[n-1]
    return x

n = eval(input("Number of equations ==> "))
x = np.zeros(n)
x,numIter,omega = gaussSeidel(iterEqs,x)
print("\nNumber of iterations =",numIter)
print("\nRelaxation factor =",omega)
print("\nThe solution is:\n",x)
#input("\nPress return to exit")

Number of equations ==> 20

Number of iterations = 259

Relaxation factor = 1.7054523107131407

The solution is:
 [-4.50000000e+00 -4.00000000e+00 -3.50000000e+00 -3.00000000e+00
 -2.50000000e+00 -2.00000000e+00 -1.50000000e+00 -9.99999997e-01
 -4.99999998e-01  2.14046747e-09  5.00000002e-01  1.00000000e+00
  1.50000000e+00  2.00000000e+00  2.50000000e+00  3.00000000e+00
  3.50000000e+00  4.00000000e+00  4.50000000e+00  5.00000000e+00]




---



---



# ЛА собственные векторы и собственные значения

**13.** Use the Jacobi method to determine the eigenvalues and eigenvectors of

 $$
\mathbf{A} =
\begin{bmatrix}
4&-1&0&1\\
-1&6&-2&0\\
0&-2&3&2\\
1&0&2&4
\end{bmatrix}
$$

Необходимость итеративного метода вычисления собственных значений:

В общем случае любой метод вычисления собственных значений обязательно включает в себя бесконечное число шагов. Это связано с тем, что нахождение собственных значений матрицы n × n эквивалентно нахождению корней ее характеристического многочлена степени n, а вычисление коэффициентов характеристического многочлена требует вычисления определителя, однако проблема нахождения корней многочлена может быть очень плохо обусловлена и для n > 4 таких корней не может быть найдено (по теореме Абеля), в общем случае, за конечное число шагов. Другими словами, мы должны рассмотреть итерационные методы, создающие на шаге k аппроксимированный собственный вектор xk, связанный с аппроксимированным собственным значением λk, которые сходятся к желаемому собственному вектору x и собственному значению λ по мере увеличения числа итераций.

In [ ]:
## module inversePower
''' lam,x = inversePower(a,s,tol=1.0e-6).
    Inverse power method for solving the eigenvalue problem
    [a]{x} = lam{x}. Returns 'lam' closest to 's' and the
    corresponding eigenvector {x}.
'''
import numpy as np
import math
from random import random
def inversePower(a,s,tol=1.0e-6):
    n = len(a)
    aStar = a - np.identity(n)*s  # Form [a*] = [a] - s[I]
    aStar = LUdecomp(aStar)       # Decompose [a*]
    x = np.zeros(n)
    for i in range(n):            # Seed [x] with random numbers
        x[i] = random()
    xMag = math.sqrt(np.dot(x,x)) # Normalize [x]
    x =x/xMag
    for i in range(50):           # Begin iterations
        xOld = x.copy()           # Save current [x]
        x = LUsolve(aStar,x)      # Solve [a*][x] = [xOld]
        xMag = math.sqrt(np.dot(x,x)) # Normalize [x]
        x = x/xMag
        if np.dot(xOld,x) < 0.0:  # Detect change in sign of [x]
            sign = -1.0
            x = -x
        else: sign = 1.0
        if math.sqrt(np.dot(xOld - x,xOld - x)) < tol:
            return s + sign/xMag,x
    print('Inverse power method did not converge')



In [ ]:
## module jacobi
''' lam,x = jacobi(a,tol = 1.0e-8).
    Solution of std. eigenvalue problem [a]{x} = lam{x}
    by Jacobi's method. Returns eigenvalues in vector {lam}
    and the eigenvectors as columns of matrix [x].
'''
import numpy as np
import math

def jacobi(a,tol = 1.0e-8): # Jacobi method

    def threshold(a):
        sum = 0.0
        for i in range(n-1):
            for j in range (i+1,n):
                sum = sum + abs(a[i,j])
        return 0.5*sum/n/(n-1)

    def rotate(a,p,k,l): # Rotate to make a[k,l] = 0
        aDiff = a[l,l] - a[k,k]
        if abs(a[k,l]) < abs(aDiff)*1.0e-36: t = a[k,l]/aDiff
        else:
            phi = aDiff/(2.0*a[k,l])
            t = 1.0/(abs(phi) + math.sqrt(phi**2 + 1.0))
            if phi < 0.0: t = -t
        c = 1.0/math.sqrt(t**2 + 1.0); s = t*c
        tau = s/(1.0 + c)
        temp = a[k,l]
        a[k,l] = 0.0
        a[k,k] = a[k,k] - t*temp
        a[l,l] = a[l,l] + t*temp
        for i in range(k):      # Case of i < k
            temp = a[i,k]
            a[i,k] = temp - s*(a[i,l] + tau*temp)
            a[i,l] = a[i,l] + s*(temp - tau*a[i,l])
        for i in range(k+1,l):  # Case of k < i < l
            temp = a[k,i]
            a[k,i] = temp - s*(a[i,l] + tau*a[k,i])
            a[i,l] = a[i,l] + s*(temp - tau*a[i,l])
        for i in range(l+1,n):  # Case of i > l
            temp = a[k,i]
            a[k,i] = temp - s*(a[l,i] + tau*temp)
            a[l,i] = a[l,i] + s*(temp - tau*a[l,i])
        for i in range(n):      # Update transformation matrix
            temp = p[i,k]
            p[i,k] = temp - s*(p[i,l] + tau*p[i,k])
            p[i,l] = p[i,l] + s*(temp - tau*p[i,l])

    n = len(a)
    p = np.identity(n,float)
    for k in range(20):
        mu = threshold(a)       # Compute new threshold
        for i in range(n-1):    # Sweep through matrix
            for j in range(i+1,n):
                if abs(a[i,j]) >= mu:
                    rotate(a,p,i,j)
        if mu <= tol: return np.diagonal(a),p
    print('Jacobi method did not converge')


In [ ]:
## module jacobi_mdf
''' lam,x = jacobi_mdf(a,tol = 1.0e-9).
    Solution of std. eigenvalue problem [a]{x} = lam{x}
    by Jacobi's method. Returns eigenvalues in vector {lam}
    and the eigenvectors as columns of matrix [x].
'''
from numpy import array,identity,diagonal,linalg as LA, dot
from math import sqrt


def jacobi_mdf(a,tol = 1.0e-9): # Jacobi method

    #a = copy.deepcopy(b)

    def maxElem(a): # Find largest off-diag. element a[k,l]
        n = len(a)
        aMax = 0.0
        for i in range(n-1):
            for j in range(i+1,n):
                if abs(a[i,j]) >= aMax:
                    aMax = abs(a[i,j])
                    k = i; l = j
        return aMax,k,l

    def rotate(a,P,k,l): # Rotate to make a[k,l] = 0
        n = len(a)
        p = identity(n)*1.0     # Initialize transformation matrix
        aDiff = a[l,l] - a[k,k]
        if abs(a[k,l]) < abs(aDiff)*1.0e-36: t = a[k,l]/aDiff
        else:
            phi = aDiff/(2.0*a[k,l])
            t = (abs(phi) + sqrt(phi**2 + 1.0))
            if phi < 0.0: t = -t
        c = 1./sqrt(t**2 + 1.0); s = t*c
        p[k,k] = c
        p[k,l] = -s
        p[l,k] = s
        p[l,l] = c
        a = dot(p.T,dot(a, p))
        P = dot(P, p)
        return a,P

    n = len(a)
    maxRot = 5*(n**2)       # Set limit on number of rotations
    p = identity(n)*1.0     # Initialize transformation matrix
    for i in range(maxRot): # Jacobi rotation loop
        aMax,k,l = maxElem(a)
        if aMax < tol: return diagonal(a),p
        a,p=rotate(a,p,k,l)
    print ('Jacobi method did not converge')




In [ ]:
## module sortJacobi
''' sortJacobi(lam,x).
    Sorts the eigenvalues {lam} and eigenvectors [x]
    in order of ascending eigenvalues.
'''
## module swap
''' swapRows(v,i,j).
    Swaps rows i and j of a vector or matrix [v].

    swapCols(v,i,j).
    Swaps columns of matrix [v].
'''
def swapRows(v,i,j):
    if len(v.shape) == 1:
        v[i],v[j] = v[j],v[i]
    else:
        v[[i,j],:] = v[[j,i],:]

def swapCols(v,i,j):
    v[:,[i,j]] = v[:,[j,i]]

def sortJacobi(lam,x):
    n = len(lam)
    for i in range(n-1):
        index = i
        val = lam[i]
        for j in range(i+1,n):
            if lam[j] > val:    # if lam[j] < val: for accending order
                index = j
                val = lam[j]
        if index != i:
            swapRows(lam,i,index)
            swapCols(x,i,index)
    return lam,x


In [ ]:
import numpy as np
%precision 9
m = 4

A = np.array([[4, -1, 0, 1], [-1, 6, -2, 0], [0, -2, 3, 2], [1, 0, 2, 4]], float)
v, w = np.linalg.eig(A)


print()
print("\n True eigenvalues: ")
print(v)
print()
print("\n True eigenvectors: ")
print(w)
print()
print("\n Computed eigenvalues: ")

lam,x = jacobi(A,tol = 1.0e-12)
print(lam)
print("\n Computed eigenvectors: ")
print(x)
print("\n Ordered result: ")
lam.setflags(write=1)
x.setflags(write=1)
lam,x = sortJacobi(lam,x)
print(lam)
print()
print(x)




 True eigenvalues: 
[0.693852066 7.647434568 3.805593731 4.853119636]


 True eigenvectors: 
[[ 0.258361268  0.300627591 -0.88907849   0.228936551]
 [ 0.327908769 -0.755350681 -0.014066258  0.567206601]
 [ 0.740785585  0.471881616  0.429105703  0.210790781]
 [-0.526271804  0.341168786  0.158776175  0.762516868]]


 Computed eigenvalues: 
[3.805593731 7.647434568 0.693852066 4.853119636]

 Computed eigenvectors: 
[[ 0.88907849  -0.300627591  0.258361268  0.228936551]
 [ 0.014066258  0.755350681  0.327908769  0.567206601]
 [-0.429105703 -0.471881616  0.740785585  0.210790781]
 [-0.158776175 -0.341168786 -0.526271804  0.762516868]]

 Ordered result: 
[7.647434568 4.853119636 3.805593731 0.693852066]

[[-0.300627591  0.228936551  0.88907849   0.258361268]
 [ 0.755350681  0.567206601  0.014066258  0.327908769]
 [-0.471881616  0.210790781 -0.429105703  0.740785585]
 [-0.341168786  0.762516868 -0.158776175 -0.526271804]]


In [ ]:
%precision 8
#!/usr/bin/python
## example

import numpy as np

s = 5.0
a = np.array([[4, -1, 0, 1], [-1, 6, -2, 0], [0, -2, 3, 2], [1, 0, 2, 4]], float)
lam,x = inversePower(a,s)
print("Eigenvalue =",lam)
print("\nEigenvector:\n",x)
#input("\nPrint press return to exit")

Eigenvalue = 4.853119635808522

Eigenvector:
 [0.22893651 0.5672066  0.2107908  0.76251688]
